# Generated by Django 3.0.5 on 2020-04-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
