# Generated by Django 3.0.5 on 2020-04-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0009_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
