# Generated by Django 3.0.5 on 2020-04-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0012_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
