# Generated by Django 3.0.5 on 2020-04-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0015_auto_20200414_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
