# Generated by Django 3.0.5 on 2020-04-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0017_auto_20200415_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
