# Generated by Django 3.0.5 on 2020-04-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0019_auto_20200418_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='quantity_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
