# Generated by Django 3.0.5 on 2020-04-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0020_orderproduct_quantity_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_price',
        ),
    ]
